server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/kafka-browser-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

kafka:
  bootstrap-servers: br201-odin-tst.io.ing.net:9093,br401-odin-tst.io.ing.net:9093
  schema-registry-url: https://sri-global-tst.ing.net:8443
  security-protocol: SSL
  ssl:
    key-store-location: /cert/vespar_cert.pfx
    key-store-password: V3sp3r.2023
    key-store-type: pkcs12
    trust-store-location: /cert/vesparapp_ipc_st_truststore.jks
    trust-store-password: 123qwe
    key-password: V3sp3r.2023
  schema-registry-ssl:
    truststore-location: /cert/vesparapp_ipc_st_truststore.jks
    truststore-password: 123qwe
    truststore-type: JKS
    keystore-location: /cert/vespar_cert.pfx
    keystore-password: V3sp3r.2023
    keystore-type: PKCS12
  consumer:
    auto-offset-reset: latest
    poll-timeout-ms: 3000
